//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("Simple Dashboard Service")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="User.SimpleDashboard.Y2006.M01, Version=0.0.0.0, Culture=neutral, PublicKeyToken=" +
    "4295554ba207a21e")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformUser {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Microsoft.Robotics.Services.SimpleDashboard.Proxy.SimpleDashboardState), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_SimpleDashboard_Proxy_SimpleDashboardState_TO_Microsoft_Robotics_Services_SimpleDashboard_SimpleDashboardState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Microsoft.Robotics.Services.SimpleDashboard.SimpleDashboardState), new global::Microsoft.Dss.Core.Attributes.Transform(Microsoft_Robotics_Services_SimpleDashboard_SimpleDashboardState_TO_Microsoft_Robotics_Services_SimpleDashboard_Proxy_SimpleDashboardState));
        }
        
        public static object Microsoft_Robotics_Services_SimpleDashboard_Proxy_SimpleDashboardState_TO_Microsoft_Robotics_Services_SimpleDashboard_SimpleDashboardState(object transformFrom) {
            global::Microsoft.Robotics.Services.SimpleDashboard.SimpleDashboardState target = new global::Microsoft.Robotics.Services.SimpleDashboard.SimpleDashboardState();
            global::Microsoft.Robotics.Services.SimpleDashboard.Proxy.SimpleDashboardState from = ((global::Microsoft.Robotics.Services.SimpleDashboard.Proxy.SimpleDashboardState)(transformFrom));
            target.Log = from.Log;
            target.LogFile = from.LogFile;
            target.TranslateScaleFactor = from.TranslateScaleFactor;
            target.RotateScaleFactor = from.RotateScaleFactor;
            return target;
        }
        
        public static object Microsoft_Robotics_Services_SimpleDashboard_SimpleDashboardState_TO_Microsoft_Robotics_Services_SimpleDashboard_Proxy_SimpleDashboardState(object transformFrom) {
            global::Microsoft.Robotics.Services.SimpleDashboard.Proxy.SimpleDashboardState target = new global::Microsoft.Robotics.Services.SimpleDashboard.Proxy.SimpleDashboardState();
            global::Microsoft.Robotics.Services.SimpleDashboard.SimpleDashboardState from = ((global::Microsoft.Robotics.Services.SimpleDashboard.SimpleDashboardState)(transformFrom));
            target.Log = from.Log;
            target.LogFile = from.LogFile;
            target.TranslateScaleFactor = from.TranslateScaleFactor;
            target.RotateScaleFactor = from.RotateScaleFactor;
            return target;
        }
    }
}
